#!/usr/bin/env bash
# bash script that installs nginx, starts it, then provides a test html page
# redirect to youtube

NEW_STRING="\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo service nginx start

sudo echo "Hello World" > /var/www/html/index.nginx-debian.html
sudo sed -i "26i $NEW_STRING" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html
sed -i "26i \\\terror_page 404 /custom_404.html;" /etc/nginx/sites-available/default

sudo service nginx restart
sudo service nginx reload
