#!/usr/bin/env bash
# bash script that installs nginx, starts it, then provides a test html page
# redirect to youtube

OLD_STRING="server_name _;"
NEW_STRING="\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
NEW_ERROR="\terror_page 404 /Http404.html;"
sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start
sudo chown -R "$USER":"$USER" /var/www/html/index.nginx-debian.html
sudo chmod -R 755 /var/www
sudo echo "Hello World" > /var/www/html/index.nginx-debian.html
sudo sed -i "/$OLD_STRING/a\\$NEW_STRING" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" >> /var/www/html/Http404.html
sudo sed -i "/$OLD_STRING/a\\$NEW_ERROR" /etc/nginx/sites-available/default
sudo service nginx restart
