#!/usr/bin/env bash
# install and configure a web-server

sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start

sudo sed -i "15i\\\tadd_header X-Served-By \$HOSTNAME;" /etc/nginx/nginx.conf

sudo service nginx restart
