#!/usr/bin/env bash
#this is a comment
echo $$ > /var/run/myscript.pid
trap "echo Y U no love me?!" SIGINT

sigtermexit()
{
    echo "I hate the kill command"
    rm /var/run/myscript.pid
    exit
}

sigquitexit()
{
    rm /var/run/myscript.pid
    exit
}

trap sigtermexit SIGTERM 
trap sigquitexit SIGQUIT

while true
do
    echo "To infinity and beyond"
    sleep 2
done
