#!/usr/bin/env bash
# its a comment
a=1
while [ "$a" -ne 11 ]
do
   if [ "$a" = 4 ]
      then echo 'bad luck'
   elif [ "$a" = 8 ]
      then echo 'good luck'
   else 
      echo 'Best School'
   fi
   ((a++))
done
