#!/usr/bin/env bash
# its a comment
hour=0
while [ "$hour" -ne 24 ]
do
   echo 'Hour:' $hour
   ((hour++))
   minute=1
   while [ "$minute" -ne 60 ]
   do
      echo $minute
      ((minute++))
   done
done
